# Generated by Django 3.1.5 on 2021-01-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nome_aluno',
            field=models.CharField(max_length=400, unique=True, verbose_name='Nome'),
        ),
    ]
