# Generated by Django 3.1.5 on 2021-01-22 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('cod_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nome_disciplina', models.CharField(max_length=300, verbose_name='Nome')),
                ('tipo_disciplina', models.CharField(choices=[('fundamental', 'Ensino Fundamental'), ('diversificada', 'Lingua Estrangeira')], max_length=30, verbose_name='Tipo de Disciplina')),
            ],
            options={
                'db_table': 'disciplina',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('cod_turma', models.AutoField(primary_key=True, serialize=False)),
                ('ano_turma', models.CharField(choices=[('1', '1º Ano'), ('2', '2º Ano'), ('3', '3º Ano'), ('4', '4º Ano'), ('5', '5º Ano'), ('6', '6º Ano'), ('7', '7º Ano'), ('8', '8º Ano'), ('9', '9º Ano'), ('eja1', 'EJA 1'), ('eja2', 'EJA 2'), ('eja3', 'EJA 3'), ('eja4', 'EJA 4')], max_length=6, verbose_name='Ano')),
                ('carga_hr', models.IntegerField(verbose_name='Oferta Anual')),
                ('disciplinas', models.ManyToManyField(to='historico.Disciplina')),
            ],
            options={
                'db_table': 'turma',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModelHistorico',
            fields=[
                ('cod_mod_historico', models.AutoField(primary_key=True, serialize=False)),
                ('nome_modelo', models.CharField(max_length=400, verbose_name='Nome do Modelo')),
                ('turma_historico', models.ManyToManyField(to='historico.Turma', verbose_name='Turmas')),
            ],
            options={
                'db_table': 'modelo_historico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricoAluno',
            fields=[
                ('cod_historico', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
                ('disciplina_historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historico.disciplina')),
                ('modelo_historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historico.modelhistorico', verbose_name='Modelo de Histórico')),
            ],
            options={
                'db_table': 'historico',
                'managed': True,
            },
        ),
    ]
