# Generated by Django 3.1.5 on 2021-01-22 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicoaluno',
            name='modelo_historico',
        ),
        migrations.AddField(
            model_name='historicoaluno',
            name='tipo_eja',
            field=models.CharField(choices=[('eja1', 'EJA1'), ('eja2', 'EJA2'), ('eja3', 'EJA3'), ('eja4', 'EJA4')], default=1, max_length=6, verbose_name='EJA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicoaluno',
            name='turma_historico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='historico.turma', verbose_name='Turmas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turma',
            name='ano_turma',
            field=models.CharField(choices=[('1', '1º Ano'), ('2', '2º Ano'), ('3', '3º Ano'), ('4', '4º Ano'), ('5', '5º Ano'), ('6', '6º Ano'), ('7', '7º Ano'), ('8', '8º Ano'), ('9', '9º Ano')], max_length=6, verbose_name='Ano'),
        ),
        migrations.DeleteModel(
            name='ModelHistorico',
        ),
    ]
