# Generated by Django 3.1.5 on 2021-01-22 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0002_auto_20210122_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoaluno',
            name='disciplina_historico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='historico.disciplina'),
        ),
        migrations.AlterField(
            model_name='historicoaluno',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='historicoaluno',
            name='tipo_eja',
            field=models.CharField(blank=True, choices=[('eja1', 'EJA1'), ('eja2', 'EJA2'), ('eja3', 'EJA3'), ('eja4', 'EJA4')], max_length=6, null=True, verbose_name='EJA'),
        ),
    ]
