# Generated by Django 3.1.5 on 2021-01-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0003_auto_20210122_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='nome_disciplina',
            field=models.CharField(max_length=300, unique=True, verbose_name='Nome'),
        ),
    ]
