# Generated by Django 3.1.5 on 2021-01-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0004_auto_20210122_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='disciplinas',
            field=models.ManyToManyField(related_name='turma_disciplinas', to='historico.Disciplina'),
        ),
    ]
