# Generated by Django 3.1.5 on 2021-01-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0005_auto_20210127_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='status_turma',
            field=models.BooleanField(default=True),
        ),
    ]
