# Generated by Django 3.1.5 on 2021-01-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0006_turma_status_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='status_turma',
            field=models.BooleanField(default=True, verbose_name='Status da turma'),
        ),
    ]
