# Generated by Django 3.1.5 on 2021-01-27 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_auto_20210127_1219'),
        ('historico', '0007_auto_20210127_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoaluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='aluno.aluno'),
        ),
    ]
