# Generated by Django 3.1.5 on 2021-02-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0008_auto_20210127_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='carga_hr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Oferta Anual'),
        ),
    ]
