# Generated by Django 3.1.5 on 2021-02-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0010_estudoshistorico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudoshistorico',
            name='resultado_estudo',
            field=models.CharField(max_length=15),
        ),
    ]
