# Generated by Django 3.1.5 on 2021-02-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0013_auto_20210208_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoaluno',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Nota'),
        ),
    ]
