# Generated by Django 3.1.5 on 2021-02-16 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0014_auto_20210216_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='disciplinas',
        ),
    ]
