# Generated by Django 3.1.5 on 2021-02-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0017_auto_20210222_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='disciplina_base',
            field=models.BooleanField(default=False),
        ),
    ]
