# Generated by Django 3.1.5 on 2021-02-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0018_disciplina_disciplina_base'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='disciplina_base',
            new_name='historico_base',
        ),
    ]
