# Generated by Django 3.1.5 on 2021-02-25 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0019_auto_20210224_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='carga_hr',
        ),
        migrations.CreateModel(
            name='OfertaAnual',
            fields=[
                ('cod_oferta_anual', models.AutoField(primary_key=True, serialize=False)),
                ('ch_hr_anual', models.IntegerField(verbose_name='Carga Horaria')),
                ('historico_oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historico.historicoaluno')),
                ('turma_oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historico.turma')),
            ],
            options={
                'db_table': 'oferta_anual',
                'managed': True,
            },
        ),
    ]
