# Generated by Django 3.1.5 on 2021-02-25 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0021_auto_20210225_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertaanual',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='ofertaanual',
            name='turma_oferta',
        ),
        migrations.AddField(
            model_name='ofertaanual',
            name='historico_aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='historico.historicoaluno'),
            preserve_default=False,
        ),
    ]
