# Generated by Django 3.1.5 on 2021-02-25 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0022_auto_20210225_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaanual',
            name='turma_ch_anual',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='historico.turma', verbose_name='Turma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ofertaanual',
            name='historico_aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historico.historicoaluno', verbose_name='Aluno'),
        ),
    ]
