# Generated by Django 3.1.5 on 2021-03-02 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_auto_20210212_1226'),
        ('historico', '0023_auto_20210225_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaanual',
            name='historico_aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno', verbose_name='Aluno'),
        ),
    ]
