# Generated by Django 3.1.5 on 2021-03-02 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0024_auto_20210301_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ofertaanual',
            old_name='historico_aluno',
            new_name='aluno',
        ),
    ]
