# Generated by Django 3.1.5 on 2021-03-02 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0025_auto_20210301_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ofertaanual',
            old_name='turma_ch_anual',
            new_name='turma',
        ),
    ]
